Algoritmo "Atividade Aula 4 - 1 "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Victor Rohod
// Autor(a)    : Bruno Rafael SR
// Data atual  : 13/05/2025
Var
n1, n2, n3 , mediaFinal : real
Inicio
//ENTRADA - 3 notas
leia(n1)
leia(n2)
leia(n3)
//PROCESSO - calcule a média
mediaFinal <- (n1 * 2 + n2 * 3 + n3 * 5) / 10
escreva("Média final : ",mediaFinal)
//SAIDA -  escreva a média final
Fimalgoritmo