Algoritmo "AULA - Correção ex3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Victor Rohod
// Autor    : Bruno Rafael SR
// Data atual  : 14/05/2025
Var
contador : inteiro

Inicio
// processo
// repetição
// saida
// (contador > 0) e (contador < 10)
contador <- 1
enquanto (contador <= 10) faca
 escreval("8 X " ,contador, "=" ,contador * 8)
 contador <- contador + 1

fimEnquanto

Fimalgoritmo