Algoritmo "Aula 7 - EX2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Victor Rohod
// Autor   :
// Data atual  : 16/05/2025
Var
numero : vetor[1..10] de inteiro
i : inteiro
Inicio
para i <- 1 ate 10 faca
    leia(numero[i])
fimPara
//enquanto (condicao) faca... contador++
// enquanto (10 > 1) faca ... i-1
para i <- 10 ate 1 passo -1 faca
  escreval(numero[i])
fimPara

Fimalgoritmo